sudo: false
language: node_js
node_js:
  - '0.12'
  - '4.2'
  - '5.0'
script: npm test
after_script: npm install -g grunt-cli yo bower && npm link && mkdir testrun && cd testrun &&  yo atomic testProk test TestRunner less true true true && grunt build
email:
    on_success: never # default: change
    on_failure: change # default: always
