default:
  - serve

serve:
  - clean:server
  - injector
  - wiredep
  - less:server
  - autoprefixer
  - babel
  - parallelize:jade
  - connect:server
  - watch

build:
   - clean:build
   - injector
   - wiredep

   - babel
   - less:dist
   - autoprefixer
   - parallelize:jade

   - copy:dist
   - useminPrepare

   - concat
   - uglify

   - imagemin
   - svgmin
   - htmlmin
   - rev
   - usemin

release:
  - bump-only
  - changelog
  - bump-commit

release:patch:
  - bump-only:patch
  - changelog
  - bump-commit

release:minor:
  - bump-only:minor
  - changelog
  - bump-commit

release:major:
  - bump-only:major
  - changelog
  - bump-commit
