default:
  - serve

serve:
  - clean:server
  - injector
  - wiredep
  - sass
  - postcss:server
  - babel
  - parallelize:jade
  - connect:server
  - watch

build:
  - clean:build
  - injector
  - wiredep
  - babel
  - sass
  - postcss:dist
  - parallelize:jade
  - copy:dist
  - useminPrepare
  - concat
  - uglify
  - imagemin
  - svgmin
  - htmlmin
  - rev
  - usemin

test:
  - build
  - connect:test
  - galen:local

release:
  - bump-only
  - changelog
  - bump-commit

release:patch:
  - bump-only:patch
  - changelog
  - bump-commit

release:minor:
  - bump-only:minor
  - changelog
  - bump-commit

release:major:
  - bump-only:major
  - changelog
  - bump-commit
