default:
  - serve

serve:
  - clean:server
  - injector
  - wiredep
  - <%= cssPreprocessor %>
  - postcss:server
  - babel
  - express
  - open
  - watch

build:
  - clean:dist
  - injector
  - wiredep
  - babel
  - <%= cssPreprocessor %>
  - postcss:dist
  - parallelize:jade
  - copy:dist
  - useminPrepare
  - concat
  - uglify
  - imagemin
  - svgmin
  - htmlmin
  - rev
  - usemin

lint:
  - eslint
  - postcss:stylelint<%if (karma) { %>
  - karma<% } %>
<%if (galen) { %>
test:
  - serve
  - galen:local
  - connect:testresults

test:production:
  - build
  - connect:dist
  - galen:local<% } %>

release:
  - bump-only
  - changelog
  - bump-commit

release:patch:
  - bump-only:patch
  - changelog
  - bump-commit

release:minor:
  - bump-only:minor
  - changelog
  - bump-commit

release:major:
  - bump-only:major
  - changelog
  - bump-commit
